homeassistant:
  # Name of the location where Home Assistant is running
  name: JimmyHome
  # Location required to calculate the time the sun rises and sets
  # 34.7832120008,113.5896400503
  latitude: 34.7831370996
  longitude: 113.5896239570
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 116
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include_dir_merge_named customize
  #packages: !include_dir_named packages
  customize_domain:
    automation:
      homebridge_hidden: true
      initial_state: on

  customize_glob:
    "switch.*":
      hidden: true
      homebridge_hidden: false

    "sensor.*":
      homebridge_hidden: true

    "fan.*":
      homebridge_hidden: true

    "sensor.illumination_*":
      hidden: true
      homebridge_hidden: true

    "binary_sensor.motion_sensor_*":
      hidden: true
      homebridge_hidden: true

    "binary_sensor.switch_*":
      hidden: true
      homebridge_hidden: true

    "group.*":
      homebridge_hidden: true

    "automation.*":
      homebridge_hidden: true

    "device_tracker.*":
      hidden: true
      homebridge_hidden: true

    "sensor.hiwifi_router_*":
      hidden: true
      homebridge_hidden: true

    "sensor.openwrt_router_*":
      hidden: true
      homebridge_hidden: true

    "script.*":
      hidden: true
      homebridge_hidden: true
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  api_password: !secret http_password
  base_url: https://www.efeichn.top:8123
  ssl_certificate: /home/pi/.homeassistant/ssl/efeichn.top.crt
  ssl_key: /home/pi/.homeassistant/ssl/efeichn.top.key
  cors_allowed_origins:
    - http://reformedreality.com
discovery:
  enable:
    - homekit
homekit:
  #auto_start: false
  filter:
    exclude_entities:
      - automation.keting_xiaomi_ap_get_led
      - automation.keting_xiaomi_ap_get_mode
      - automation.keting_xiaomi_ap_set_led
      - automation.keting_xiaomi_ap_set_mode
      - automation.woshi_xiaomi_ap_get_led
      - automation.woshi_xiaomi_ap_get_mode
      - automation.woshi_xiaomi_ap_set_led
      - automation.woshi_xiaomi_ap_set_mode
      - automation.mam_go_home
      - automation.qmi_goto_bed
      - automation.report_weather_status
      - automation.cuckoo_clock
      - automation.some_light_auto_off
      - automation.light_go_to_sleep
      - automation.somebody_at_home_with_sunset_in_holidayhome_open_light
      - automation.mam_and_dad_go_home_workday_open_light
      - automation.close_keting_light
      - automation.open_keting_light
      #- group.all_devices
      - device_tracker.androidef354cffcb55a9b3
      - device_tracker.android9ec21c22b1e42fa5
      - device_tracker.androidd90f1750e3a3928c
      - device_tracker.androidf94fd32ac22765bf
      - device_tracker.androidd90f1750e3a3928c
      - device_tracker.androiddd747c41c780dba7
      - device_tracker.androidef354cffcb55a9b3
      - device_tracker.androidf94fd32ac22765bf
      - device_tracker.androidfe6359f4de25919d
      - device_tracker.android6d5740df58ac8663
      - device_tracker.e4c48330ad3f
      - device_tracker.fc1a11506266
      - device_tracker.meizu
      - device_tracker.oppok1
      - device_tracker.vivo_x7plus
      - device_tracker.vivo_y51a
      - device_tracker.vivox9splusl
      - device_tracker.huawei_nova_2s5163314069
      - device_tracker.fc1a11506266
      - device_tracker.redmi5plushongmisho
      - device_tracker.vivox9splusl
      - device_tracker.v1732a
      - device_tracker.r9plus
      - device_tracker.r9plus_2
      - device_tracker.iphone
      - device_tracker.jiqidmistoryv1_miio59682032
      - device_tracker.rmproplus5a6cc2
      - device_tracker.rock64
      - device_tracker.skyboxq0102125271d7ad129de6
      - device_tracker.tmallgenie
      - device_tracker.xiaob
      - device_tracker.chenfeidembp
      - device_tracker.fuqingqngdeipad
      - device_tracker.esp_6818cd
      - device_tracker.esp_6822b8
      - device_tracker.esp8266_zhuwo
      - device_tracker.redminote2hongmisho
       ## livingroom
      - device_tracker.xiaomilivingroom
      - switch.keting_xiaomi_ap_buzzer
      - switch.keting_xiaomi_ap_childlock
      - sensor.keting_xiaomi_ap_humid
      - sensor.keting_xiaomi_ap_temp
      - fan.keting
      - switch.keting_room_light_light_sleep
      ## woshi 
      - device_tracker.xiaomibedroom
      - switch.woshi_xiaomi_ap_buzzer
      - switch.woshi_xiaomi_ap_childlock
      - sensor.woshi_xiaomi_ap_humid
      - sensor.woshi_xiaomi_ap_temp
      - fan.woshi
      - switch.zhuwo_room_light_light_sleep
      - switch.ciwo_room_light_light_sleep
# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically

# Allows you to issue voice commands from the frontend in enabled browsers

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
# Text to speech
tts:
  - platform: google
    language: 'zh-cn'
  - platform: baidu
    #app_id，api_key，secret_key从百度云上注册得到
    app_id: 6786368
    api_key: guwmwrNwc7RiDScPK7wgb19n
    secret_key: IDdbf8M5powM5ViY93A9REsOqLNqRXiT
    #speed：语速0-9（缺省5）
    #pitch：语调0-9（缺省5）
    #volume：音量0-15（缺省5）
    #person：声音（0：女，1：男，3：百度合成，4：百度合成，缺省0）
    speed: 4
    pitch: 5
    volume: 13
    person: 0

    #ifttt:
    #  key: cibXF2TxJNFGSNpINKAyc-
mqtt:
  password: 1qaz2wsx

panel_iframe:
  homebridge:
    title: HomeBridge
    icon: mdi:apple
    url: https://www.efeichn.top:8125
  kodi:
    title: KODI
    icon: mdi:kodi
    url: https://www.efeichn.top:8890
    #  weblink:
    #    title: SmartHome
    #    icon: mdi:home-automation
    #    url: https://www.efeichn.top:1234
panel_custom:
  - name: inkwavemap
    sidebar_title: '墨澜地图'
    sidebar_icon: mdi:map
    url_path: inkwavemap
    #twilio:
    #  account_sid: ACc5a95806884fc02d2be2c59b3f23c0d8
    #  auth_token: 4c5e2c4e6721c220e1fb4335e1c691ba
notify:
    #  - platform: twilio_sms
    #    name: twilio_sms
    #    from_number: "+18038280909"

# Cloud
#cloud:
# log
#logger:
#  default: warning
#  logs:
#    homeassistant.components.homekit: debug
#    pyhap.accessory_driver: debug
#    #pyhap: debug
logger:
  # 可能的日志严重程度是: notset, debug, info, warn, warning, error, fatal, critical
  default: info
  logs:
    aiohttp.access: critical
    aiohttp.server: critical
    homeassistant.core: error
    homeassistant.components.automation: warn
    homeassistant.components.binary_sensor: warn
    homeassistant.components.device_tracker: warn
    homeassistant.components.switch: debug
    homeassistant.components.discovery: warn
    homeassistant.components.http: warn
    homeassistant.components.media_player: warn
    homeassistant.components.recorder: warn
    homeassistant.components.sensor.command_line: warn
    homeassistant.components.shell_command: debug
    homeassistant.helpers.script: warn
    homeassistant.helpers.entity: warn
    custom_components.device_tracker.hiwifi: warn
    custom_components.sensor.moji_weather: warn
    requests.packages.urllib3.connectionpool: error
    requests.packages.urllib3: error
    requests.packages.urllib3.http.client: error
group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
fan: !include_dir_merge_list fan
shell_command: !include_dir_merge_named shell_command
conversation: !include_dir_merge_named conversation
intent_script: !include_dir_merge_named intent_script
media_player: !include_dir_merge_list media_player
