title: Jimmy Chen智能家居系统
views:
    # View tab title.
  - icon: mdi:weather-rainy
    title: 郑州室外天气状况
    #panel: true
    # Makes the first card fill the view
    cards:
      - type: entities
        title: 自然
        entities:
          - sun.sun
          - sensor.heweather_tmp_max
          - sensor.heweather_tmp_min
          - sensor.heweather_fl
          - sensor.heweather_tmp
          - sensor.heweather_hum
          - sensor.heweather_pop
          - sensor.heweather_cond_txt
          - sensor.heweather_pcpn
          - sensor.heweather_pres
          - sensor.heweather_vis
      - type: entities
        title: 风
        entities:
          - sensor.heweather_wind_sc
          - sensor.heweather_wind_dir
          - sensor.heweather_wind_spd
      - type: entities
        title: 空气质量
        entities:
          - sensor.heweather_pm25
          - sensor.heweather_pm10
          - sensor.heweather_main
          - sensor.heweather_aqi
          - sensor.heweather_qlty
      - type: entities
        title: 生活指数
        entities: 
          - sensor.heweather_comf
          - sensor.heweather_cw
          - sensor.heweather_drsg
          - sensor.heweather_flu
          - sensor.heweather_sport
          - sensor.heweather_trav
          - sensor.heweather_uv
  - icon: mdi:home-assistant
    title: 空气净化器
    cards:
      - type: glance
        title: 客厅空气净化器
        entities:
          - fan.keting
          - switch.keting_xiaomi_ap_buzzer
          - switch.keting_xiaomi_ap_childlock
          - sensor.keting_xiaomi_ap_aqi
          - sensor.keting_xiaomi_ap_temp
          - sensor.keting_xiaomi_ap_humid
          - sensor.keting_xiaomi_filter_used
          - sensor.keting_xiaomi_filter_remaining
      - type: glance
        title: 卧室空气净化器
        entities:
          - fan.woshi
          - switch.woshi_xiaomi_ap_buzzer
          - switch.woshi_xiaomi_ap_childlock
          - sensor.woshi_xiaomi_ap_aqi
          - sensor.woshi_xiaomi_ap_temp
          - sensor.woshi_xiaomi_ap_humid
          - sensor.woshi_xiaomi_filter_used
          - sensor.woshi_xiaomi_filter_remaining
