- platform: template
  fans:
    kayee_fan:
      value_template: "{{ states('input_boolean.dinning_fan') }}"
      speed_template: "{{ states('input_number.fan_speed') | int}}"        
      turn_on:
        service: script.kayee_fan_slow
      turn_off:
        service: script.kayee_fan_off
      set_speed:
        service: input_number.set_value
        entity_id: input_number.fan_speed
        data_template:
          speed: "{{ speed }}"
      speeds:
        - '0'
        - '1'
        - '2'
        - '3'
