- platform: broadlink
  host: 192.168.88.166
  mac: '78:0f:77:5a:6c:c2'
  switches:
    air_conditioner:
      friendly_name: "客厅空调"
      command_on: 'JgAkAQABJ5QWEhUTFRIVNxYSFTcVExQTFTcVExUSFTcWEhUTFBMVExUTFBMVExUTFBMVNxUTFRIVExUTFRIVExU3FRMUNxUTFRMVNxUSFQACkhYSFBMVExUSFRMVExUSFRMVExUSFRMVExUSFRMVNxUTFRIVExUTFRIVExUTFRIVExUTFBMVExUTFDcVNxU3FTcVAAUjAAEolBUSFRMVExU2FRMVNxUTFRIVNxUTFRMVNhUTFRMVEhUTFRMVEhUTFRMVExQ3FRMVExUSFRMVExUSFTcVNxU3FRMVEhU3FRMVAAKRFhIVExUSFRMVExUSFRMVExUSFRMVExUSFRMVExUSFRMVExQTFRMVExQTFTcVExUSFRMVExUSFRMVNxUTFTcVNhUADQUAAAAA' 
      command_off: 'JgAkAQABJ5QWEhUTFRIVNxYSFTcVExQTFTcVExUSFTcWEhUTFBMVExUTFBMVExUTFBMVNxUTFRIVExUTFRIVExU3FRMUNxUTFRMVNxUSFQACkhYSFBMVExUSFRMVExUSFRMVExUSFRMVExUSFRMVNxUTFRIVExUTFRIVExUTFRIVExUTFBMVExUTFDcVNxU3FTcVAAUjAAEolBUSFRMVExU2FRMVNxUTFRIVNxUTFRMVNhUTFRMVEhUTFRMVEhUTFRMVExQ3FRMVExUSFRMVExUSFTcVNxU3FRMVEhU3FRMVAAKRFhIVExUSFRMVExUSFRMVExUSFRMVExUSFRMVExUSFRMVExQTFRMVExQTFTcVExUSFRMVExUSFRMVNxUTFTcVNhUADQUAAAAA'
