- platform: broadlink
  host: 192.168.88.6
  mac: '78:0F:77:5A:6C:C2'
  switches:
    lg_tv:
      command_on: 'JgBgAAABKpIUEhQSFBAVERURFREVEBURFTYVNRU2FDUUNRU1FREVNRURFREVERUQFREUEhQSFBEVNRQ1FDUWNRQ1FTUVNRU1FAAFSgABKUkVAAxbAAEpSRUADFsAASlJFgANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKpIUEhQSFBAVERURFREVEBURFTYVNRU2FDUUNRU1FREVNRURFREVERUQFREUEhQSFBEVNRQ1FDUWNRQ1FTUVNRU1FAAFSgABKUkVAAxbAAEpSRUADFsAASlJFgANBQAAAAAAAAAA'
