- platform: command_line
  switches:
    living_room_light_on_off_status:
      ## 192.168.88.9 living_room
      command_on: "/usr/bin/curl -X GET  'http://192.168.88.141:1234/room?roomid=keting&state=on'"
      command_off: "/usr/bin/curl -X GET 'http://192.168.88.141:1234/room?roomid=keting&state=off'"
      command_state: "/usr/bin/curl -X GET 'http://192.168.88.141:1234/room?roomid=keting&state=stats'"
      value_template: '{{ value == "on" }}'
      #command_on: "/usr/bin/curl -X GET  http://192.168.88.9/keting?state=kai"
      #command_off: "/usr/bin/curl -X GET http://192.168.88.9/keting?state=guan"
      #command_state: "/usr/bin/curl -X GET http://192.168.88.9/keting?state=stats"
      #value_template: '{{ value == "1" }}'
    zhuwo_room_light_on_off_status:
      ## 192.168.88.10 zhuwo_room
      command_on: "/usr/bin/curl -X GET  'http://192.168.88.141:1234/room?roomid=zhuwo&state=on'"
      command_off: "/usr/bin/curl -X GET 'http://192.168.88.141:1234/room?roomid=zhuwo&state=off'"
      command_state: "/usr/bin/curl -X GET 'http://192.168.88.141:1234/room?roomid=zhuwo&state=stats'"
      value_template: '{{ value == "on" }}'
      #command_on: "/usr/bin/curl -X GET  http://192.168.88.10/zhuwo?state=kai"
      #command_off: "/usr/bin/curl -X GET http://192.168.88.10/zhuwo?state=guan"
      #command_state: "/usr/bin/curl -X GET http://192.168.88.10/zhuwo?state=stats"
      #value_template: '{{ value == "1" }}'
    ciwo_room_light_on_off_status:
      ## 192.168.88.13 ciwo_room
      command_on: "/usr/bin/curl -X GET  'http://192.168.88.141:1234/room?roomid=ciwo&state=on'"
      command_off: "/usr/bin/curl -X GET 'http://192.168.88.141:1234/room?roomid=ciwo&state=off'"
      command_state: "/usr/bin/curl -X GET 'http://192.168.88.141:1234/room?roomid=ciwo&state=stats'"
      value_template: '{{ value == "on" }}'
      #command_on: "/usr/bin/curl -X GET  http://192.168.88.141/ciwo?state=kai"
      #command_off: "/usr/bin/curl -X GET http://192.168.88.141/ciwo?state=guan"
      #command_state: "/usr/bin/curl -X GET http://192.168.88.141/ciwo?state=stats"
      #value_template: '{{ value == "1" }}'
