- platform: template
  switches:
    keting_xiaomi_ap_buzzer:
      value_template: "{{ is_state_attr('fan.keting', 'buzzer', true) }}"
      turn_on:
        service: fan.xiaomi_miio_set_buzzer_on
        entity_id: fan.keting
      turn_off:
        service: fan.xiaomi_miio_set_buzzer_off
        entity_id: fan.keting
- platform: template
  switches:
    keting_xiaomi_ap_childlock:
      value_template: "{{is_state_attr('fan.keting', 'child_lock', true)}}"
      turn_on:
        service: fan.xiaomi_miio_set_child_lock_on
        entity_id: fan.keting
      turn_off:
        service: fan.xiaomi_miio_set_child_lock_off
        entity_id: fan.keting
- platform: template
  switches:
    woshi_xiaomi_ap_buzzer:
      value_template: "{{ is_state_attr('fan.woshi', 'buzzer', true) }}"
      turn_on:
        service: fan.xiaomi_miio_set_buzzer_on
        entity_id: fan.woshi
      turn_off:
        service: fan.xiaomi_miio_set_buzzer_off
        entity_id: fan.woshi
- platform: template
  switches:
    woshi_xiaomi_ap_childlock:
      value_template: "{{is_state_attr('fan.woshi', 'child_lock', true)}}"
      turn_on:
        service: fan.xiaomi_miio_set_child_lock_on
        entity_id: fan.woshi
      turn_off:
        service: fan.xiaomi_miio_set_child_lock_off
        entity_id: fan.woshi
