# GaoDe Map API
- platform: gaode_travel_time
  name: driving_to_company
  api_key: 9d1f337261ff34e672c3b75d5fe7058c
  friendly_name: 从家去公司
  #homebridge_hidden: false
  travel_mode: driving
  strategy: 0       #optional, 0-9, default 0 速度最快
  origin:
    longitude_latitude: 113.596374,34.7827
    #city: 郑州
    #address: 正商百合里
  destination:
    longitude_latitude: 113.805421,34.795648
    #city: 郑州
    #address: 专利局审协河南中心

- platform: gaode_travel_time
  name: driving_to_home
  api_key: 9d1f337261ff34e672c3b75d5fe7058c
  friendly_name: 从公司回家
  #homebridge_hidden: false
  travel_mode: driving
  strategy: 0       #optional, 0-9, default 0 速度最快
  origin:
    longitude_latitude: 113.805421,34.795648
    #city: 郑州
    #address: 专利局审协河南中心
  destination:
    longitude_latitude: 113.596374,34.7827
    #city: 郑州
    #address: 正商百合里
- platform: template
  sensors: 
    to_company_time:
      friendly_name: 去公司
      value_template: "{{ states('sensor.driving_to_company')|int }}"
      unit_of_measurement: 分钟
    to_home_time:
      friendly_name: 回家
      value_template: "{{ states('sensor.driving_to_home')|int }}"
      unit_of_measurement: 分钟
