- platform: HeWeather
  city: zhengzhou
  #aqi_city: zhengzhou
  appkey: d7c331e73816479f847ee321a4e619fb
  options:
    - fl
    - tmp
    - cond_txt
    - wind_spd
    - hum
    - pcpn
    - pres
    - vis
    - wind_sc
    - aqi
    - main
    - qlty
    - pm10
    - pm25
    - comf
    - cw
    - drsg
    - flu
    - sport
    - trav
    - uv
    - wind_dir
    - tmp_max
    - tmp_min
    - pop
#- platform: template
#  sensors:
#    tmp:
#      friendly_name: "温度"
#      device_class: temperature
#      value_template: "{{ states('sensor.heweather_tmp') }}"
#    hum:
#      friendly_name: "湿度"
#      device_class: humidity
#      value_template: "{{ states('sensor.heweather_hum') }}"
