- platform: HeWeather
  city: zhengzhou
  aqi_city: zhengzhou
  appkey: d7c331e73816479f847ee321a4e619fb
  options:
    - fl
    - tmp
    - cond_txt
    - wind_spd
    - hum
    - pcpn
    - pres
    - vis
    - wind_sc
    - aqi
    - main
    - qlty
    - pm10
    - pm25
    - comf
    - cw
    - drsg
    - flu
    - sport
    - trav
    - uv
    - wind_dir
    - tmp_max
    - tmp_min
    - pop
