- alias: adjust_diningroom_fan_speed
  trigger:
    platform: state
    entity_id: input_number.fan_speed
  action:
    - service: switch.broadlink_send_packet_192_168_88_166
      data_template:
        packet: >-
          {if trigger.to_state.state | int ==0}"sQY0AA0jDQABbSUMJQwNJA0jJQwNIw0jDSQNIw0jDSMlDCUMJQwNIw0jDSMlDCUMDSMlDCUMDSMAAAAA"
          {if trigger.to_state.state | int ==1}"sQY0ACUMJQsOIw4jJQwNIw4jDiMNIw4jDiMlCyUMJQsOIw0jDSMlCyUMDSMlCw0jDiMOIw0AAW0AAAAA"
          {if trigger.to_state.state | int ==2}"sQc0AA4jDSMOIyULJQslCw4jDSMOIyULJQsNIw0jDiMlDA0jDgABbSULJQsOIw0jJQwNIw4jDSMAAAAA"
          {if trigger.to_state.state | int ==3}"sgY0ACUMJQsNIw4jJQsOIw4jDiMOIw0jDiMlCyUMJQwNIw4jDSMlCyULDiMOIyULJQsOIw0AAW0AAAAA"
