- alias: some_light_auto_off
  hide_entity: true
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.keting_room_light_quanliang,switch.keting_room_light_changyedeng,switch.keting_room_light_ming,switch.keting_room_light_an,switch.keting_room_light_riguangse,switch.keting_room_light_nuanbaise,switch.zhuwo_room_light_quanliang,switch.zhuwo_room_light_changyedeng,switch.zhuwo_room_light_ming,switch.zhuwo_room_light_an,switch.zhuwo_room_light_riguangse,switch.zhuwo_room_light_nuanbaise,switch.ciwo_room_light_quanliang,switch.ciwo_room_light_changyedeng,switch.ciwo_room_light_ming,switch.ciwo_room_light_an,switch.ciwo_room_light_riguangse,switch.ciwo_room_light_nuanbaise
    from: 'off'
    to: 'on'
  action:
    - delay: 0:0:10
    - service: switch.turn_off
      data_template:
        entity_id: > 
          {{ trigger.entity_id }}
- alias: light_go_to_sleep
  hide_entity: true
  initial_state: true
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: switch.turn_on
    entity_id:
      - switch.keting_room_light_light_sleep
      - switch.zhuwo_room_light_light_sleep
      - switch.ciwo_room_light_light_sleep
